project:
  type: website
  output-dir: docs

website:
  title: "Shelby Level"
  favicon: sl_logo_transparent.png
  navbar:
    logo: white-sl-logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/shelbylevel
        aria-label: GitHub


format:
  html:
    theme: lux
    css: lux-bootstrap.css
    toc: true

editor: visual

