project:
  type: website
  output-dir: _site

website:
  #title: "Shelby Level"
  favicon: logos/sl_sticker.png
  navbar:
    #title: "SHELBY LEVEL"
    logo: logos/white-sl-logo-final-crop.png
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About Me"
      - href: blog.qmd
        text: Blog
      - href: myprojects.qmd
        text: "Past Projects"
      - icon: github
        href: https://github.com/shelbylevel
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/shelby-level-ches-791791232/
        aria-label: LinkedIn
  page-footer:
    background: light # or dark
    left:
      - "Copyright 2024, Shelby Level"
    right:
      - icon: github
        href: https://github.com/shelbylevel
      - icon: linkedin
        href: https://www.linkedin.com/in/shelby-level-ches-791791232/
  #reader-mode: true

#format:
  #html:
    #theme: sl-theme-light.scss
    #css: sl-style.css
    #toc: true

format:
  html:
    theme:
      -  lux
      -  css/lux-variables.scss
    css: css/sl-lux-bootstrap.css
    toc: true
    page-layout: full

editor: source

