project:
  type: website
  output-dir: docs

website:
  title: "Shelby Level"
  favicon: logos/sl_sticker.png
  navbar:
    title: "SHELBY<span class='icon-line'></span>LEVEL"
    logo: logos/white-sl-logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/shelbylevel
        aria-label: GitHub


format:
  html:
    theme: lux
    css: lux-bootstrap.css
    toc: true

editor: visual

