project:
  type: website
  output-dir: _site

website:
  title: "Shelby Level"
  favicon: logos/sl_sticker.png
  navbar:
    title: "<span class='first-name' >SHELBY</span><span class='icon-line' ></span><span class ='icon-line2'></span> <span class='last-name' >LE</span><span class='v' >v</span> <span class='last-name2' >EL</span>"
    right:
      - href: index.qmd
        text: "About Me"

      - href: blog.qmd
        text: Blog
      - href: myprojects.qmd
        text: "Past Projects"
      - icon: github
        href: https://github.com/shelbylevel
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/shelby-level-ches-791791232/
        aria-label: LinkedIn
  page-footer:
    background: light # or dark
    left:
      - "Copyright 2024, Shelby Level"
    right:
      - icon: github
        href: https://github.com/shelbylevel
      - icon: linkedin
        href: https://www.linkedin.com/in/shelby-level-ches-791791232/
  #reader-mode: true

#format:
  #html:
    #theme: sl-theme-light.scss
    #css: sl-style.css
    #toc: true

format:
  html:
    theme:
      -  lux
      -  css/sl-lux-variables.scss
    css:
      #-  css/sl-bootstrap.min.css #header color
      -  css/sl-lux-bootstrap.css #bold font weight and hover color for header
    toc: true
    page-layout: full

editor: source

